import AppKit

@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var activity: NSObjectProtocol?
    private let store: HistoryStore
    private let settings: AppSettings

    init(store: HistoryStore, settings: AppSettings) {
        self.store = store
        self.settings = settings
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        // Отключаем App Nap, иначе таймер опроса буфера засыпает в фоне.
        activity = ProcessInfo.processInfo.beginActivity(
            options: .userInitiatedAllowingIdleSystemSleep,
            reason: "Clipboard history monitoring"
        )
        // .common — чтобы опрос шёл и во время меню/скролла/ресайза.
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        if let activity {
            ProcessInfo.processInfo.endActivity(activity)
        }
        activity = nil
    }

    /// Пометить буфер как «свой» после программной вставки, чтобы не дублировать в историю.
    func acknowledgeOwnChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        guard let item = readPasteboard() else { return }
        store.add(item)
    }

    private func readPasteboard() -> ClipboardItem? {
        let types = pasteboard.types ?? []

        if settings.skipPasswords {
            let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
            let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
            let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
            if types.contains(concealed) || types.contains(transient) || types.contains(autoGenerated) {
                return nil
            }
        }

        // 1. Файлы (Finder и т.п.)
        let opts: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: opts) as? [URL],
           !urls.isEmpty {
            return .makeFile(paths: urls.map { $0.path })
        }

        let plain = pasteboard.string(forType: .string)
        let hasText = plain?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false

        // 2. Изображение (когда нет текстового представления). Типы буфера для картинок
        //    бывают разными (png/tiff/jpeg/gif/…), поэтому читаем напрямую через NSImage.
        if !hasText, let png = imagePNG(from: pasteboard) {
            return .makeImage(png: png)
        }

        // 3. RTF (форматированный текст)
        if let rtf = pasteboard.data(forType: .rtf), let plain, !plain.isEmpty {
            return .makeRTF(rtf: rtf, plain: plain)
        }

        // 4. Обычный текст
        if hasText, let plain {
            return .makeText(plain)
        }

        return nil
    }

    private func imagePNG(from pasteboard: NSPasteboard) -> Data? {
        // 1. Прямой PNG из буфера (copy image в браузере и т.п.).
        if let png = pasteboard.data(forType: .png) {
            return png
        }
        guard let img = NSImage(pasteboard: pasteboard) else { return nil }
        // 2. Через TIFF-представление (скриншоты macOS кладут TIFF).
        if let tiff = img.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        // 3. Запасной путь — пересобрать из CGImage.
        var rect = CGRect(origin: .zero, size: img.size)
        if let cg = img.cgImage(forProposedRect: &rect, context: nil, hints: nil) {
            let rep = NSBitmapImageRep(cgImage: cg)
            return rep.representation(using: .png, properties: [:])
        }
        return nil
    }
}
